[package]
name = "conway"
version = "0.1.0"
authors = ["daemoz"]

[dependencies]
rand = "0.3.15"
ncurses = { version = "5.86.0", optional = true }
argparse = { version = "*", optional = true }

[[bin]]
name = "conway-cli"
path = "cli/src/main.rs"
required-features = ["binaries"]

[features]
binaries = ["ncurses", "argparse"]
