[Input_Cell_Patterns]
neighbors = "../folder/neighbors.cw"


[Initial_States]
horizontal_lines = "../folder2/horizontal_lines.cw"
vertical_lines = "../folder2/vertical_lines.cw"
checkerboard = "../folder2/checkerboard.cw"

[Rulesets]
decay = "../folder3/decay.cw"

# $ conway config_file.txt -fc Yellow -r Decay -i DesignFromConfigFile
